#version 450

#include "compute/sdf_common.comp"

layout(local_size_x = THREAD_GROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

// One thread per each cell.
void main() {
    int numSdfCells = g_NumCellsX * g_NumCellsY * g_NumCellsZ;

    int sdfCellIndex = gl_GlobalInvocationID.x;
    if (sdfCellIndex >= numSdfCells) return;

    uint distance = g_SignedDistanceField[sdfCellIndex];
    g_SignedDistanceField[sdfCellIndex] = IFloatFlip3(distance);
}
